### ISSUE TITLE
[Feature Request] Ability to increase voice messages quality

### ISSUE THREAD

**Issue by groozchique** [Nekogram/Nekogram-issue-tracker#103]
**Is your feature request related to a problem? Please describe.**
Voice messages quality on TAndroid is poor compared to Telegram iOS due low sample rate.

**Describe the solution you'd like**
https://github.com/DrKLO/Telegram/commit/a461d529f6e844fd8dc561f8eb06e16db1bfe2da

**Comment by groozchique** [comment]
Telegram will say: "Ask marketing team" :p
You can close the issue if you feel like you won't do anything about it, it's fine :)

**Comment by NekoInverter** [comment]
In next release
