### ISSUE TITLE
Battery drain fix :))

### ISSUE THREAD

**Issue by abn3li** [Nekogram/Nekogram-issue-tracker#104]
I have faced a battery drain not too much but its noticeable.. hope you will enhance battery life .

Another feature request : 
Image sending quality make it 100% by default ❤️

Keep you hard work 
Thanks

**Comment by NekoInverter** [comment]
> I have faced a battery drain not too much but its noticeable.. hope you will enhance battery life .

🤔 I don't experience this problem

**Comment by abn3li** [comment]
So its only with me 🥺 ? 
Do you recommend me to do a clean format to my phone ?

**Comment by nekunei** [comment]
This can happend with your Battery phone.
In the case, My battery is OK.

**Comment by abn3li** [comment]
> This can happend with your Battery phone.
> In the case, My battery is OK.

Yeah exactly .. I don't know why but after a clean format and for the first SOT everything is good 
So i think that i were using an app that draining my battery without notice from me 
Any way iam gonna close the thread
