### ISSUE TITLE
It is impossible to open left menu panel using swipe when "all chats" tab is hidden and all chats displayed.

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#106]
**Describe the bug**
It is impossible to open left menu panel using swipe when "all chats" tab is hidden and all chats displayed.

**To Reproduce**
1. Have several folders
2. Hide "all chats"
3. Restart app, first custom tab is active
4. Press back to see all chats list
5. You can't open left panel by swiping right

**Expected behavior**
Left panel can be opened from any chat list

**Smartphone (please complete the following information):**
 - Device: HTC One M9
 - OS: Android 7
 - Version 6.2.0.1

**Comment by NekoInverter** [comment]
I know this feature is buggy :(

**Comment by NekoInverter** [comment]
[ElementsBattle - resourcepack 1.16.2.zip](https://github.com/Nekogram/Nekogram-issue-tracker/files/5144845/ElementsBattle.-.resourcepack.1.16.2.zip)
