### ISSUE TITLE
Record voice message button is stuck on short press when internal camera is disabled

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#107]
**Describe the bug**
Record voice message button is stuck on short press when internal camera is disabled

**To Reproduce**
1. Disable internal camera
2. Open any dialog
3. Short tap record button
4. It remains pressed and recording

**Expected behavior**
Like on official client with disabled internal camera, short press-release should cancel voice message (it's too short to be meaningful). For sticking it there is a swipe-up action.

**Smartphone (please complete the following information):**
 - Device: HTC One M9
 - OS: Android 7
 - Version 6.2.0.1

**Comment by NekoInverter** [comment]
Try to disabled confirm sending voice message

**Comment by 0xCA** [comment]
> 
> 
> Try to disabled confirm sending voice message

It is indeed a necessary condition for stucking. With confirm disabled recording behaviour is stock-like.

**Comment by 0xCA** [comment]
So is this stucking intended with confirmation enabled?
It still looks like a bug to me because confirmation should only affect what happens after the message is recorded, not before.
