### ISSUE TITLE
NoQuote forward breaks albums

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#108]
**Describe the bug**
NoQuote forward breaks albums.

**To Reproduce**
1. Find some album
2. NoQuote forward it
3. Now it's not an album, but a separate messages

**Expected behavior**
Albums are forwarded as albums regardless of quoute|noquote forward.
Also it should keep an album when forwarding only a part of an album (not all album medias are selected).

**Smartphone (please complete the following information):**
 - Device: HTC One M9
 - OS: Android 7
 - Version 6.2.0.1

**Comment by NekoInverter** [comment]
Fixed in next release
