### ISSUE TITLE
Neko option to disable media preview in dialogs list

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#109]
**Is your feature request related to a problem? Please describe.**
There is a new feature in 6.3 that displays a tiny media thumbnail at dialogue list. It is a good feature but it really increases an information density which overloads perception. So it'd be great to have an option to disable it, reverting back to general media icons (image or video).

**Describe the solution you'd like**
Neko option to enable old interface for these thumbnails.

**Describe alternatives you've considered**
Can't think of any

**Comment by NekoInverter** [comment]
There is option to disable them

**Comment by 0xCA** [comment]
Somehow I actually missed it, sorry
