### ISSUE TITLE
When logged in as bot there is an endlessly spinning loader at the bottom of the chat list

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#110]
**Describe the bug**
When logged in as bot there is an endlessly spinning loader at the bottom of the chat list.
When you have only a several chats at your bot, you always see it on a main screen which is annoying.

**To Reproduce**
1. Log in as bot
2. Scroll chat list to bottom
3. See an infinite loading spinner

**Expected behavior**
Spinner is displayed only before first bot api response. If no chats, hide it. If some chats, hide it as well.
Alternatively do not display it at all.

**Smartphone (please complete the following information):**
 - Device: HTC One M9
 - OS: Android 7
 - Version 6.2.0.1

**Comment by NekoInverter** [comment]
There is no point for hiding it

**Comment by 0xCA** [comment]
Like I said, when you have <7 dialogues, it's really annoying to constantly see.
Also it makes visual activity tracking really hard. Without that pointless spinner you can just watch for any movement on the screen, it will be a new|edited message. But it's much harder to notice with this thing.
