### ISSUE TITLE
Option to disable bot account background update

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#111]
**Is your feature request related to a problem? Please describe.**
In a situation of a really bad coverage or low battery it'd be great to have only selected account active.
If I'm not mistaken, for now bot accounts are inactive when app is not opened and all of them are active when the app is opened.

**Describe the solution you'd like**
Add some system-wide Neko switch to completely disable any activity from non-selected accounts so that only one is active.
None of others should use network or drain battery.

**Describe alternatives you've considered**
Add per-account switch for accounts to mark which of them should be active when they're not selected.

**Additional context**
Applies to both bot and regular accounts.

**Comment by NekoInverter** [comment]
There isn't much activity for non-selected acccount to drain your battery 🤔

**Comment by 0xCA** [comment]
About battery: imagine a popular bot with about a 1000 active users that you're debugging. You want this thing to be active only when you're using it. Otherwise you have to log out after any debug session. Rare issue, yes.

About traffic: when you're using a bot (or any other account) it's convenient to have it auto-download all compressed images. To just better see what's going on without tapping everything to download. The thing is, auto-download is active when another account is active. And if you're on a train for example, this will heavily affect your active account experience as it will try to download images from all accounts.
