### ISSUE TITLE
Display seconds at message details section

### ISSUE THREAD

**Issue by 0xCA** [Nekogram/Nekogram-issue-tracker#113]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to see when exactly the message was sent or edited, but I have to see it on desktop or copy message JSON and convert timestamp manually which isn't convenient.

**Describe the solution you'd like**
Display message **Date** and **Edited** datetime with seconds.
`dd.mm.yy at hh:mm:ss`

**Describe alternatives you've considered**
For more details, display milliseconds as well. But in most cases seconds alone should be enough.
`dd.mm.yy at hh:mm:ss.SSS`

**Additional context**
![image](https://user-images.githubusercontent.com/11984323/88878135-abc86b80-d240-11ea-80c7-883c16110e30.png)
I created this issue a while back but it seems that my bad internet connection caused it not to be posted.

**Comment by NekoInverter** [comment]
In next release
