### ISSUE TITLE
opening of all links with quick opening

### ISSUE THREAD

**Issue by xunil89** [Nekogram/Nekogram-issue-tracker#114]
I wanted to ask if it was possible to introduce a native function that is on telegram x, the function of forcing the opening of all links with quick opening.
![Screenshot_20200806-114436_Telegram_X_1](https://user-images.githubusercontent.com/14961235/89518522-4d206600-d7db-11ea-8131-68d23b922c7a.png)

**Comment by NekoInverter** [comment]
in next release
