### ISSUE TITLE
Categories to separate chats

### ISSUE THREAD

**Issue by Eri1305** [Nekogram/Nekogram-issue-tracker#116]
**Is your feature request related to a problem? Please describe.**
I have many chats and many channels, bots, groups, then I would love to be able to sort them into categories so I can find them more easily. 

Excuse me, my native language is Spanish. I'm sorry if you don't understand something. 

**Describe the solution you'd like**
I'd appreciate it if you'd place categories, don't confuse folders. I know you can make folders, but it's very tedious to have a lot of them, I'd prefer categories that can be accessed on a button. 

**Describe alternatives you've considered**
To be guided you could tell them to see the categories of a green Telegram Api(Pls Mssngr) In which they have categories. 

**Additional context**
Screenshots of what I'm talking about, in case you don't understand me.

![inCollage_20200830_082734657](https://user-images.githubusercontent.com/70475443/91660436-77dca200-ea9b-11ea-9e47-11bff913792d.jpg)

![inCollage_20200830_082807286](https://user-images.githubusercontent.com/70475443/91660442-82973700-ea9b-11ea-92fb-27bb2922fbe9.jpg)

![inCollage_20200830_083118037](https://user-images.githubusercontent.com/70475443/91660457-9c387e80-ea9b-11ea-9424-f0917a86f40f.jpg)

![inCollage_20200830_083140318](https://user-images.githubusercontent.com/70475443/91660460-a5c1e680-ea9b-11ea-8454-e13a4585773b.jpg)

![inCollage_20200830_083206009](https://user-images.githubusercontent.com/70475443/91660463-abb7c780-ea9b-11ea-83e1-458257a8d15b.jpg)

Thank you very much if you decide to listen to my request.

**Comment by RememberTheAir** [comment]
This looks veeeeery redundant with cloud-synced folders

**Comment by NekoInverter** [comment]
no
