### ISSUE TITLE
Add new proxy

### ISSUE THREAD

**Issue by owner** [Nekogram/Nekogram-issue-tracker#119]
1️⃣ Standard: 
tg: tg://proxy?server=proxy.mtproto.org&port=443&secret=11112222333344445555666677778888

2️⃣ Secure (TLS): 
tg: tg://proxy?server=proxy.mtproto.org&port=443&secret=dd11112222333344445555666677778888

3️⃣ Recommended (FakeTLS): 
tg: tg://proxy?server=proxy.mtproto.org&port=443&secret=ee111122223333444455556666777788887777772e636c6f7564666c6172652e636f6d

**Comment by NekoInverter** [comment]
？
