### ISSUE TITLE
Ability to disable proximity events for video/audio messages

### ISSUE THREAD

**Issue by wight554** [Nekogram/Nekogram-issue-tracker#94]
This functionality exists in telegram x and useful for people with ultrasound proximity sensor (like xiaomi mi mix 2 in my case)
In telegram x it's under "Playback through earpiece" options
![Screenshot_20200618-234559_Telegram_X](https://user-images.githubusercontent.com/26501410/85070150-faa0d100-b1bd-11ea-9a0b-b106d154fad8.png)

**Comment by NekoInverter** [comment]
In next release
