### ISSUE TITLE
希望播放视频时，app 后台 锁屏 后，自动停止播放

### ISSUE THREAD

**Issue by Forty-nine** [Nekogram/Nekogram-issue-tracker#95]
**Is your feature request related to a problem? Please describe.**
现在 app 后台 锁屏 后，播放的视频依旧会播放

**Describe the solution you'd like**
 app 后台 锁屏 后，播放的视频自动暂停

**Describe alternatives you've considered**

**Additional context**

**Comment by NekoInverter** [comment]
In next release
